/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import com.google.cloud.firestore.WriteResult;
import com.google.firebase.cloud.FirestoreClient;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;

public class MENU extends javax.swing.JFrame {


    public MENU() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMenuExit = new javax.swing.JButton();
        btnHOD = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        newtimebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 50, 71));

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(167, 183, 196));
        jLabel1.setText("WELCOME TO THE COMPUTER DEPARTMENT");

        l2.setFont(new java.awt.Font("URW Chancery L", 3, 30)); // NOI18N
        l2.setForeground(new java.awt.Color(167, 183, 196));
        l2.setText("TIMETABLE GENERATOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(236, 236, 236)
                                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(41, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(121, 213, 225));

        btn1.setBackground(new java.awt.Color(228, 199, 225));
        btn1.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        btn1.setForeground(new java.awt.Color(45, 22, 22));
        btn1.setText("SE TIMETABLE");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn1ActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btn2.setBackground(new java.awt.Color(228, 199, 225));
        btn2.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        btn2.setForeground(new java.awt.Color(49, 35, 35));
        btn2.setText("TE TIMETABLE");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn2ActionPerformed(evt);
                } catch (ExecutionException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        btn3.setBackground(new java.awt.Color(228, 199, 225));
        btn3.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        btn3.setForeground(new java.awt.Color(40, 31, 31));
        btn3.setText("BE TIMETABLE");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn3ActionPerformed(evt);
                } catch (ExecutionException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        btnMenuExit.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        btnMenuExit.setText("EXIT");
        btnMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuExitActionPerformed(evt);
            }
        });

        btnHOD.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        btnHOD.setText("H.O.D LOGIN");
        btnHOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnHODActionPerformed(evt);
                } catch (ExecutionException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        btn4.setBackground(new java.awt.Color(228, 199, 225));
        btn4.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        btn4.setForeground(new java.awt.Color(40, 31, 31));
        btn4.setText("PROF TIMETABLE");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        newtimebtn.setFont(new java.awt.Font("URW Chancery L", 1, 36)); // NOI18N
        newtimebtn.setText("NEW TIMETABLE");
        newtimebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    newtimebtnActionPerformed(evt);
                } catch (ExecutionException e) {
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnHOD)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                        .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                        .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                        .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                        .addComponent(newtimebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnHOD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(newtimebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

   static String[][] SEESUBJECTS=new String[5][8];
   static String[][] TEESUBJECTS=new String[5][8];
   static String[][] BEESUBJECTS=new String[5][8];

    ArrayList<String> retrievedSEsub=new ArrayList<>();
    ArrayList<String> retrievedTEsub=new ArrayList<>();
    ArrayList<String> retrievedBEsub=new ArrayList<>();

    ArrayList<SeTimetable> retrievedSEsubjects=new ArrayList<>();
    ArrayList<SeTimetable> retrievedTEsubjects=new ArrayList<>();
    ArrayList<SeTimetable> retrievedBEsubjects=new ArrayList<>();

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
        Laraib um=new Laraib();
        String s="TIMETABLE OF SE";

        ALLCLASSRETRIEVESUBJECTS ();
        String batchSE[]={"S1","S2","S3","S4"};
        TIMES fa =new TIMES(SEESUBJECTS,practical.PracSE,s,batchSE);
        fa.setVisible(true);
        this.dispose();
    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) throws ExecutionException, InterruptedException {


        Laraib um=new Laraib();
        String batchTE[]={"T1","T2","T3","T4"};
        String s="TIMETABLE OF TE";




        ALLCLASSRETRIEVESUBJECTS ();
        TIMET fa =new TIMET(TEESUBJECTS,practical.PracTE,s,batchTE);
        fa.setVisible(true);
        this.dispose();
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) throws ExecutionException, InterruptedException {
        Laraib um=new Laraib();

        String s="TIMETABLE OF BE";
        String batchBE[]={"B1","B2","B3","B4"};




        ALLCLASSRETRIEVESUBJECTS ();
        TIMESB fa =new TIMESB(BEESUBJECTS,practical.PracBE,s,batchBE);
        fa.setVisible(true);
        this.dispose();
    }

    private void btnMenuExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    private void btnHODActionPerformed(java.awt.event.ActionEvent evt) throws ExecutionException, InterruptedException {
        // TODO add your handling code here:
        Laraib um=new Laraib();
        this.dispose();
        if(login.t==0) {
            login lo = new login();
            lo.setVisible(true);
        }
        else
        {

            ALLCLASSRETRIEVESUBJECTS ();
            Master ma = new Master(MENU.SEESUBJECTS, MENU.TEESUBJECTS, MENU.BEESUBJECTS);
            ma.setVisible(true);
            this.dispose();


        }
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        profftime pt=new profftime();
        pt.setVisible(true);
        this.dispose();
    }





    private void newtimebtnActionPerformed(java.awt.event.ActionEvent evt) throws ExecutionException, InterruptedException {
        // TODO add your handling code here:

        DeleteOldSubjects();


        newTime ne=new newTime();

        ne.setVisible(true);
        this.dispose();
    }



    void DeleteOldSubjects() throws ExecutionException, InterruptedException {

        Firestore db = FirestoreClient.getFirestore();
        ApiFuture<QuerySnapshot> future1 =db.collection("SE").get();

        List<QueryDocumentSnapshot> documents=future1.get().getDocuments();
        for(QueryDocumentSnapshot document:documents){
            retrievedSEsub.add(document.getId());

            System.out.println(document.getId());
        }

        for(int i=0;i<retrievedSEsub.size();i++) {
            ApiFuture<WriteResult> writeResult = db.collection("SE").document(retrievedSEsub.get(i)).delete();
// ...
        }

        ApiFuture<QuerySnapshot> future2 =db.collection("TE").get();

        List<QueryDocumentSnapshot> documentss=future2.get().getDocuments();
        for(QueryDocumentSnapshot document:documentss){
            retrievedTEsub.add(document.getId());

            System.out.println(document.getId());
        }
        for(int i=0;i<retrievedTEsub.size();i++) {
            ApiFuture<WriteResult> writeResult = db.collection("TE").document(retrievedTEsub.get(i)).delete();
// ...
        }



        ApiFuture<QuerySnapshot> future3 =db.collection("BE").get();

        List<QueryDocumentSnapshot> documentsss=future3.get().getDocuments();
        for(QueryDocumentSnapshot document:documentsss){
            retrievedBEsub.add(document.getId());

            System.out.println(document.getId());
        }
        for(int i=0;i<retrievedBEsub.size();i++) {
            ApiFuture<WriteResult> writeResult = db.collection("BE").document(retrievedBEsub.get(i)).delete();
// ...
        }

    }



    void ALLCLASSRETRIEVESUBJECTS () throws ExecutionException, InterruptedException {

        Firestore db = FirestoreClient.getFirestore();
        ApiFuture<QuerySnapshot> future1 =db.collection("SEE_Timetable").get();

        List<QueryDocumentSnapshot> documents=future1.get().getDocuments();
        for(QueryDocumentSnapshot document:documents){
            retrievedSEsubjects.add(document.toObject(SeTimetable.class));

            System.out.println(document.getId());
        }


        SEESUBJECTS=newTIMETablemethods.arraylisttostring(retrievedSEsubjects);


        ApiFuture<QuerySnapshot> future2 =db.collection("TEE_Timetable").get();

        List<QueryDocumentSnapshot> documentsT=future2.get().getDocuments();
        for(QueryDocumentSnapshot document:documentsT){
            retrievedTEsubjects.add(document.toObject(SeTimetable.class));

            System.out.println(document.getId());
        }
        TEESUBJECTS=newTIMETablemethods.arraylisttostring(retrievedTEsubjects);


        ApiFuture<QuerySnapshot> future3 =db.collection("BEE_Timetable").get();

        List<QueryDocumentSnapshot> documentsB=future3.get().getDocuments();
        for(QueryDocumentSnapshot document:documentsB){
            retrievedBEsubjects.add(document.toObject(SeTimetable.class));

            System.out.println(document.getId());
        }
        BEESUBJECTS=newTIMETablemethods.arraylisttostring(retrievedBEsubjects);


    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnHOD;
    private javax.swing.JButton btnMenuExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l2;
    private javax.swing.JButton newtimebtn;
    // End of variables declaration
}
